import assert from 'node:assert/strict';
import {mkdtemp,writeFile,readFile,chmod} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {visibleWidth} from '@earendil-works/pi-tui';
import type {Block} from '../../src/types';
import {runHerdrScenario} from './herdr-runner';

// Observe the real platform opener without launching a browser or contacting a host.
const capture=await mkdtemp(join(tmpdir(),'property-opener-'));
const opened=join(capture,'opened.txt');
const quotedLog="'"+opened.replaceAll("'", "'\\''")+"'";
await writeFile(join(capture,'xdg-open'),`#!/bin/sh\nprintf '%s\\n' "$1" >> ${quotedLog}\n`);
await chmod(join(capture,'xdg-open'),0o700);
const originalPath=process.env.PATH;
process.env.PATH=`${capture}:${originalPath}`;

const url='https://example.test/threads/DEMO-762?thread=123.456&channel=alpha#reply';
let result;
try { result=await runHerdrScenario({name:'property-actions',async prepare(){},async run(s){
 const terminal=await s.attachClient();await terminal.resize(220,65);
 const destination=await s.client.request<Block>({action:'create',text:'PROPERTY DESTINATION\n\nArrived from an internal property link.'});
 const mixed=`Read https://example.test/one then [Second](https://example.test/two) and [Inside](pi-outliner://block/${destination.id})`;
 const source=await s.client.request<Block>({action:'create',text:`PROPERTY ACTIONS\n[state::waiting] [state::ready] [link::${url}]\nlinks:: ${mixed}\n\nBody after properties.`});
 const clients=await s.registrations();
 const detail=clients.find(c=>c.runtime?.paneId===s.panes.detail)!;
 const tree=clients.find(c=>c.runtime?.paneId===s.panes.tree)!;
 await s.client.request({action:'navigation.dispatch',sourceClientId:tree.clientId,sourceRegion:'tree',intent:'open',target:{kind:'block',blockId:source.id},destination:{clientId:detail.clientId,region:'detail'}});
 await s.focus(s.panes.detail);await s.waitVisible(s.panes.detail,'PROPERTY ACTIONS');
 await s.keys(s.panes.detail,'tab','enter');
 await s.waitVisible(s.panes.detail,'waiting');
 const point=async(label:string)=>{
  const matches=(r:string)=>r.includes(label)&&!(label==='Copy'&&r.includes('Copy value'));
  const frame=await s.waitFor('attached property target: '+label,terminal.visible,f=>f.split('\n').some(matches));
  const rows=frame.split('\n');const row=rows.findIndex(matches);
  if(row<0)throw Error('Visible property control missing: '+label);
  return {row,column:visibleWidth(rows[row]!.slice(0,rows[row]!.indexOf(label)))};
 };
 const click=async(label:string)=>{const p=await point(label);await terminal.write(`\x1b[<0;${p.column+2};${p.row+1}M\x1b[<0;${p.column+2};${p.row+1}m`);};
 const transcript=join(s.artifactDirectory,'attached-client.ansi');
 const copied=async(action:()=>Promise<void>,expected:string)=>{
  const before=(await readFile(transcript,'utf8')).length;await action();
  const values=await s.waitFor('property clipboard',async()=>[...(await readFile(transcript,'utf8')).slice(before).matchAll(/\x1b\]52;[^;]*;([A-Za-z0-9+/=]+)/g)].map(m=>Buffer.from(m[1]!,'base64').toString()),v=>v.includes(expected));
  assert.deepEqual(values,[expected]);
 };
 await copied(()=>click('ready'),'ready');
 await copied(()=>s.keys(s.panes.detail,'y'),'ready');
 await s.checkpoint('01-plain-value-copy');
 await copied(()=>click('Copy'),url);
 await click('https://example.test');
 await s.waitFor('external URL exactly once',async()=>readFile(opened,'utf8').catch(()=>''),v=>v===url+'\n');
 await s.checkpoint('02-url-follow-and-copy');
 const drag=await point('https://example.test');
 await copied(()=>terminal.write(`\x1b[<0;${drag.column+1};${drag.row+1}M\x1b[<32;${drag.column+6};${drag.row+1}M\x1b[<0;${drag.column+6};${drag.row+1}m`),'https:');
 assert.equal(await readFile(opened,'utf8'),url+'\n','Dragging must not follow a link');
 await click('dedicated Detail');
 const dedicated=await s.waitFor('dedicated property reader',s.registrations,cs=>cs.some(c=>c.clientId!==detail.clientId&&c.role==='detail'));
 const reader=dedicated.find(c=>c.clientId!==detail.clientId&&c.role==='detail')!;
 const pane=await s.adoptDetached(reader.clientId);
 await s.keys(s.panes.detail,'p');
 await s.waitFor('inline inspector closed',()=>s.visible(s.panes.detail),f=>!f.includes('waiting'));
 await s.focus(pane);await s.waitVisible(pane,'Properties');
 await s.keys(pane,'tab','tab');await s.waitVisible(pane,'ready');
 await copied(()=>click('ready'),'ready');
 await s.keys(pane,'tab');await s.waitVisible(pane,'Copy');
 await copied(()=>click('Copy'),url);
 await s.keys(pane,'o');
 await s.waitFor('keyboard follows same URL',async()=>readFile(opened,'utf8'),v=>v===url+'\n'+url+'\n');
 await s.checkpoint('02b-dedicated-properties');
 await terminal.resize(125,55);
 await s.waitFor('narrow property layout',()=>s.visible(pane),v=>v.includes('Copy')&&!v.includes(url));
 await copied(()=>s.keys(pane,'y'),url);
 await s.keys(pane,'e');await s.waitVisible(pane,'✎');
 await s.keys(pane,'escape');
 assert.equal((await s.client.request<Block>({action:'get',blockId:source.id})).revision,source.revision);
 await s.checkpoint('03-narrow-copy-edit-cancel');
 await s.keys(pane,'tab');await s.waitVisible(pane,'Second');
 await click('Second');
 await s.waitFor('second embedded link',async()=>readFile(opened,'utf8'),v=>v.endsWith('https://example.test/two\n'));
 await copied(()=>s.keys(pane,'y'),mixed);
 await s.keys(pane,'shift+tab','o');
 await s.waitFor('first embedded link by keyboard',async()=>readFile(opened,'utf8'),v=>v.endsWith('https://example.test/one\n'));
 await s.keys(pane,'tab','o');
 await s.waitFor('second embedded link by keyboard',async()=>readFile(opened,'utf8'),v=>v.endsWith('https://example.test/one\nhttps://example.test/two\n'));
 await s.checkpoint('04-independent-embedded-targets');
 await s.client.request({action:'navigation.link.set',source:{clientId:reader.clientId,region:'detail'},destination:{clientId:detail.clientId,region:'detail'}});
 await s.keys(pane,'tab','o');
 await s.waitVisible(s.panes.detail,'Arrived from an internal property link.');
 assert.equal((await s.client.request<Block>({action:'get',blockId:source.id})).revision,source.revision);
 assert.ok((await s.registrations()).some(c=>c.clientId===reader.clientId&&c.currentTarget?.kind==='block'&&c.currentTarget.blockId===source.id));
 await s.checkpoint('05-copy-then-internal-navigation');
 await s.record('coverage',{clipboard:'Exact OSC52 payload, not physical clipboard paste',external:'Actual platform command with recording receiver; no browser/network'});
}});
} finally {process.env.PATH=originalPath;}

console.log(JSON.stringify(result));if(result.status!=='passed')process.exitCode=1;
