import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {join} from 'node:path';
import {visibleWidth} from '@earendil-works/pi-tui';
import type {Block, VirtualBranchOrder, WorkingSelection} from '../../src/types';
import {runHerdrScenario} from './herdr-runner';

const result=await runHerdrScenario({name:'working-selection',async prepare(){},async run(s){
  const terminal=await s.attachClient(); await terminal.resize(210,64);
  const tree=s.panes.tree;
  const create=(text:string)=>s.client.request<Block>({action:'create',text});
  const view=await create('SELECTION CANDIDATES\n[type::virtual-branch] [query::fixture=selection]');
  const blocks:Block[]=[];
  for(const letter of 'ABCDE')blocks.push(await create(`Candidate ${letter}\n[fixture::selection] [page::selection-${letter}]`));
  const ids=blocks.map(b=>b.id);
  await s.client.request({action:'virtual.occurrences.reorder',viewId:view.id,orderedBlockIds:ids});
  const hub=await create(`SELECTION HUB\n\n!((`+view.id+'))');
  const menu=async(label:string)=>{
    await s.keys(tree,'?'); await s.waitVisible(tree,'Find:');
    await s.text(tree,label); await s.waitVisible(tree,'Find: '+label); await s.keys(tree,'enter');
  };
  await s.focus(tree); await s.revealTree(tree,view.id); await menu('focus branch');
  await s.waitVisible(tree,'Candidate E');
  await s.keys(tree,'down');
  // Discover and start from the ordinary menu, without creating a named session.
  await menu('Select / unselect item'); await s.waitVisible(tree,'1 selected');
  await s.checkpoint('01-first-selection');
  const clickMark=async(title:string)=>{
    const frame=await s.waitFor('checkbox for '+title,()=>terminal.visible(),f=>f.split('\n').some(line=>line.includes('[ ] '+title)));
    const lines=frame.split('\n');const row=lines.findIndex(line=>line.includes('[ ] '+title));
    const column=visibleWidth(lines[row]!.slice(0,lines[row]!.indexOf('[ ] '+title)));
    await terminal.write(`\x1b[<0;${column+2};${row+1}M\x1b[<0;${column+2};${row+1}m`);
  };
  await clickMark('Candidate C'); await s.waitVisible(tree,'2 selected');
  await s.keys(tree,'down','down','down','down','x'); await s.waitVisible(tree,'3 selected');
  const owner=(await s.registrations()).find(c=>c.runtime?.paneId===tree&&c.role==='tree')!;
  const saved=await s.client.request<WorkingSelection>({action:'working-selection.get',ownerClientId:owner.clientId});
  assert.deepEqual(saved.targets.map(t=>t.blockId),[ids[0],ids[2],ids[4]]);
  await s.checkpoint('02-keyboard-pointer-three-items');
  await menu('Move selected top');
  const ordered=[ids[0]!,ids[2]!,ids[4]!,ids[1]!,ids[3]!];
  await s.waitFor('rank applied',()=>s.client.request<VirtualBranchOrder>({action:'virtual.occurrences.order',viewId:view.id}),o=>o.blockIds.join()===ordered.join());
  await s.waitVisible(tree,'Moved selected top');
  await s.checkpoint('03-ranked-in-tree');
  const transcript=join(s.artifactDirectory,'attached-client.ansi');
  const before=(await readFile(transcript,'utf8')).length;
  await menu('Copy selected page links');
  const expected='[[selection-A]]\n[[selection-C]]\n[[selection-E]]';
  await s.waitFor('exact clipboard links',async()=>[...(await readFile(transcript,'utf8')).slice(before).matchAll(/\x1b\]52;[^;]*;([A-Za-z0-9+/=]+)/g)].map(m=>Buffer.from(m[1]!,'base64').toString()),values=>values.includes(expected));
  await s.keys(tree,'X'); await s.waitVisible(tree,'Read · Candidate C');
  await s.text(tree,'Read · Candidate C'); await s.waitVisible(tree,'Find: Read · Candidate C');
  await s.checkpoint('04-read-choice'); await s.keys(tree,'enter');
  await s.waitVisible(tree,'Preview · Candidate C');
  assert.equal((await s.client.request<WorkingSelection>({action:'working-selection.get',ownerClientId:owner.clientId})).targets.length,3);
  await s.checkpoint('04-read-keeps-selection');
  await s.revealTree(tree,hub.id); await s.keys(tree,'enter');
  await s.waitVisible(s.panes.detail,'Candidate E');
  const frame=await s.visible(s.panes.detail);
  const positions=['A','C','E','B','D'].map(letter=>frame.indexOf('Candidate '+letter));
  assert.ok(positions.every(p=>p>=0)&&positions.every((p,i)=>i===0||p>positions[i-1]!),'Hub embed follows the ranked branch');
  await s.checkpoint('05-hub-reflects-ranking');
  const receiver=await create('');
  const detail=(await s.registrations()).find(c=>c.runtime?.paneId===s.panes.detail&&c.role==='detail')!;
  await s.client.request({action:'ui.command.send',command:{targetClientId:detail.clientId,command:'edit',target:{kind:'block',blockId:receiver.id}}});
  await s.waitVisible(s.panes.detail,'Editing');
  await s.text(s.panes.detail,expected); await s.keys(s.panes.detail,'ctrl+s');
  await s.waitFor('copied links paste exactly',()=>s.client.request<Block>({action:'get',blockId:receiver.id}),b=>b.text===expected);

  await s.focus(tree); await terminal.resize(140,40);
  await s.waitVisible(tree,'3 selected'); await menu('Clear selected items');
  await s.waitFor('selection durably cleared',()=>s.client.request({action:'working-selection.get',ownerClientId:owner.clientId}),selection=>selection===null);
  await s.waitFor('clear removes selection controls',()=>s.visible(tree),f=>!f.includes('3 selected'));
  for(const block of blocks)assert.deepEqual(await s.client.request<Block>({action:'get',blockId:block.id}),block);
  await s.checkpoint('06-narrow-clear');
  await s.record('coverage',{input:'Herdr keys and attached-terminal SGR pointer clicks',clipboard:'Exact OSC52 payload; physical host paste not claimed',targets:ids,ranked:ordered});
}});
console.log(JSON.stringify(result));if(result.status!=='passed')process.exitCode=1;
